In [1]:
print("Hello MIT")

Hello MIT


In [2]:
## Vector Addition
import numpy as np
a = np.array([3,5])
b =  np.array([2,7])
a+b

array([ 5, 12])

In [3]:
## Transpose of vector -- 1 D Vector 

# Method 1
a = np.array([1,2])
a = a.reshape(-1,1)
a

# method 2
a = np.array([1,2,3])
a = a[:, np.newaxis]  # Adds a new axis to make it a column vector
a


array([[1],
       [2],
       [3]])

In [4]:
## Traspose of n dimensional vector wher n>=2
b = np.array([[1,2,3],[4,5,6]])
b= b.T
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
# Scaler Multplication in a Vector 
a = np.array([1,2,3])
scaler =  5
a =  scaler*a
a

array([ 5, 10, 15])

In [6]:
a = np.array([1,2,3])
scaler =  2
a = a.reshape(-1,1)
a = a*scaler
a

array([[2],
       [4],
       [6]])

In [7]:
## Scaler Multilplication in specific row 
scaler =  10
a[1] = scaler*a[1]
a

array([[ 2],
       [40],
       [ 6]])

In [8]:
## Scaler  Multiplication in a matrix 
## Specific Row multiplication by a scaler in a particular row 
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 2
matrix = matrix * scalar
sacler =  10
matrix[0] = matrix[0] * sacler
print(matrix)


[[20 40 60]
 [ 8 10 12]
 [14 16 18]]


In [9]:
### Element wise multiplication in matrix

a = np.array([[1,2],
              [2,3]])
b = np.array([[5,6],
              [7,8]])
a*b 

array([[ 5, 12],
       [14, 24]])

In [14]:
w =  np.array([1,5,0])
w = w.reshape(-1,1)
x = np.array([8,2])
w*x

array([[ 8,  2],
       [40, 10],
       [ 0,  0]])

In [23]:
def add_two_lists(a, b):
    an = []
    for i, j in zip(a,b):
        an.append(i+j)
    return an

ans = add_two_lists([1, 2, 3], [4, 5, 6])
print(ans)
    

[5, 7, 9]


In [24]:
a = np.array([1,2,3])
a  = a+2
a

array([3, 4, 5])