In [48]:
print("Hello World")

Hello World


In [49]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [50]:
import numpy


In [51]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [52]:
## NUMPY alias
import numpy as np
arr = np.array([1,2,2,3,3])
arr

array([1, 2, 2, 3, 3])

In [53]:
# Version of Numpy Installed 
np.__version__

'1.26.4'

In [54]:
## NUMPY Array is a ndArray type
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [55]:
## Image 2
arr = np.array((1, 2, 3, 4, 5))

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [56]:
## Dimesions of Arrays 
print("*************** 0 Dimesnsional Array / Scaler Value ***********************")
arr = np.array(6)
print("Array is " , arr)
print("Dimesion of Array is " ,arr.ndim)\


print("\n\n*************** 1 Dimesnsional Array  ***********************")
arr = np.array((1,2,7,33,4,9))
print("Array is " , arr)
print("Dimesion of Array is " ,arr.ndim)


print("\n\n*************** 2 Dimesnsional Array  ***********************")
arr = np.array(((1,2,7),(33,4,9)))
print("Array is " , arr)
print("Dimesion of Array is " ,arr.ndim)

*************** 0 Dimesnsional Array / Scaler Value ***********************
Array is  6
Dimesion of Array is  0


*************** 1 Dimesnsional Array  ***********************
Array is  [ 1  2  7 33  4  9]
Dimesion of Array is  1


*************** 2 Dimesnsional Array  ***********************
Array is  [[ 1  2  7]
 [33  4  9]]
Dimesion of Array is  2


In [57]:
### Creating N Dimensional Array 

import numpy as np 

arr = np.array((1,2,3,4),ndmin=10)
print("Array is " , arr)
print("Dimesion of Array is " ,arr.ndim)

Array is  [[[[[[[[[[1 2 3 4]]]]]]]]]]
Dimesion of Array is  10


In [58]:
## Data Type in NUMPY 

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [59]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [60]:
import numpy as np
## Creating an array with type
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [61]:
import numpy as np
# Creating an array with size values 
arr = np.array([1, 2, 3, 4], dtype='i8')

print(arr)
print(arr.dtype)

[1 2 3 4]
int64


In [62]:
import numpy as np
# if value conversion is not possible it would result in error
# arr = np.array(['a', '2', '3'], dtype='i')

In [63]:
import numpy as np
## Conversion of value from one type to another of numpy array 
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [64]:
# Image 5
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [65]:
# Image 5

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [66]:
### Checcking Bases 
# Image 6
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [67]:
### Shape of Data 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [68]:
arr = np.array(8)
arr.shape

()

In [69]:
arr = np.array((8,9))
arr.shape

(2,)

In [70]:
### REshape  --> Conversion of an 1D array to some some dimension using reshape method 
# Image 7, 8 
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [71]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)
# Since it returns a array it is view not a copy 

[1 2 3 4 5 6 7 8]


In [72]:
# Image 8
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2,-1)
print(newarr)

print("********************\n\n")
newarr = arr.reshape(2,2,-1)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]]
********************


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flattening the ndArrays

In [73]:
import numpy as np
arr = np.array([[1, 2, 3, 4],[ 5, 6, 7, 8]])

newarr = arr.reshape(-1)
print(newarr)
print(newarr.base) ## It is returning the arrow so it is returning the view not copy of original Array


[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


### Iterating the Array 

In [74]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [75]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [76]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y,end=' ')
  print()

1 2 3 
4 5 6 


In [77]:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [78]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z,end=' ')
    print()
  print()

1 2 3 
4 5 6 

7 8 9 
10 11 12 



In [79]:
## nditer
''' 
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

'''
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [80]:
''' 
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

'''

arr = np.array([[1, 2, 3],[4,5,6]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


### ARRAY JOINING

In [90]:
import numpy as np

''' 

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

'''

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2),axis=0)

print(arr)

[1 2 3 4 5 6]


In [91]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [95]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [97]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [98]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
