In [1]:
print("Tensors ")

Tensors 


In [2]:
import numpy as np

In [3]:
### 0 Dimensional Tensor
a = np.array(4)

In [4]:
a

array(4)

In [ ]:
a.ndim ## it gives number of dimensions of a tensor 
# tensor and n dimensional array is same .... 

1

### 1 d Tensor 

In [6]:
a = np.array([1,2,3])

In [7]:
a.ndim

1

In [8]:
a

array([1, 2, 3])

Here "a" is 1D tensor i.e; 1D tensor is also called as Vector 
but ??? 
here vector  has 3 dimension and tensor has 1 dimension....



1D tensor is collection of scalers / 0d tensors... 

2,
3,
4
are 0D tensors / Scalers
but when we combine them to a single data structure it becomes 1D tensor i.e; Vector  

### 2D Tensors

Multiple vectors form 2D Tensors 

In [9]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [10]:
mat.ndim

2

In [11]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 3D Tensor

In [12]:
three_dim_tensor = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print(three_dim_tensor.ndim)


3


In [13]:
print(three_dim_tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


### 4 Dimensional Tensor

In [14]:
four_dim_tensor = np.array(
    [
        [   
            [
                [1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
            ],
            [
                [13, 14, 15, 16],
                [17, 18, 19, 20],
                [21, 22, 23, 24]
            ]
        ],
        [   
            [
                [1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
            ],
            [
                [13, 14, 15, 16],
                [17, 18, 19, 20],
                [21, 22, 23, 24]
            ]
        ],
        [   
            [
                [1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
            ],
            [
                [13, 14, 15, 16],
                [17, 18, 19, 20],
                [21, 22, 23, 24]
            ]
        ]
    ]
)

In [15]:
four_dim_tensor

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]],


       [[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]],


       [[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]])

In [16]:
four_dim_tensor.ndim

4

## Rank, Axis Dimension and Shape and Size

In [17]:
# number of axis = number of dimension = rank

In [18]:
four_dim_tensor.shape

(3, 2, 3, 4)

In [19]:
four_dim_tensor.size

72

In [20]:
three_dim_tensor.ndim

3

In [21]:
three_dim_tensor.shape


(2, 3, 4)

In [22]:
three_dim_tensor.size

24

In [23]:
# Dimensional of a tensor is different from dimension of a particular tensor like in [1,2,3] is 1 dimensional tensor but it is 3 dimensional vector 